
export const GET_SIZES = "GET_SIZES";
export const GET_SIZES_BY_QUERY = "GET_SIZES_BY_QUERY";
export const GET_SIZE_BY_ID = "GET_SIZE_BY_ID";
export const ADD_SIZE = "ADD_SIZE";
export const UPDATE_SIZE = "UPDATE_SIZE";
export const DELETE_SIZE = "DELETE_SIZE";
export const DELETE_SIZES_BY_RANGE = "DELETE_SIZES_BY_RANGE";

export const BIND_SIZE_DATA = "BIND_SIZE_DATA";

export const SELECTED_SIZE_NULL = "SELECTED_SIZE_NULL";


export const OPEN_SIZE_SIDEBAR = "OPEN_SIZE_SIDEBAR";
export const OPEN_SIZE_SIDEBAR_FOR_EDIT = "OPEN_SIZE_SIDEBAR_FOR_EDIT";
export const DROP_DOWN_SIZES = "DROP_DOWN_SIZES";

export const GET_STYLE_SIZES_DROP_DOWN = "GET_STYLE_SIZES_DROP_DOWN";


export const GET_SIZES_BY_SIZE_GROUP_ID = "GET_SIZES_BY_SIZE_GROUP_ID";

export const IS_SIZE_DATA_LOADED = "IS_SIZE_DATA_LOADED";
export const IS_SIZE_DATA_ON_PROGRESS = "IS_SIZE_DATA_ON_PROGRESS";
export const IS_SIZE_DATA_SUBMIT_PROGRESS = "IS_SIZE_DATA_SUBMIT_PROGRESS";
