
export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const GET_DEPARTMENTS_BY_QUERY = "GET_DEPARTMENTS_BY_QUERY";
export const GET_DEPARTMENT_BY_ID = "GET_DEPARTMENTS_BY_ID";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const DELETE_PRODUCT_CATEGORY_FROM_DEPARTMENT = "DELETE_PRODUCT_CATEGORY_FROM_DEPARTMENT";
export const DELETE_DEPARTMENTS_BY_RANGE = "DELETE_DEPARTMENTS_BY_RANGE";
export const DEPARTMENT_INSTANT_CREATE = "DEPARTMENT_INSTANT_CREATE";

export const SELECTED_DEPARTMENT_NULL = "SELECTED_DEPARTMENT_NULL";

export const BIND_STYLE_DEPARTMENT = "BIND_STYLE_DEPARTMENT";

export const OPEN_DEPARTMENT_SIDEBAR = "OPEN_DEPARTMENT_SIDEBAR";
export const OPEN_DEPARTMENT_SIDEBAR_FOR_EDIT = "OPEN_DEPARTMENT_SIDEBAR_FOR_EDIT";
export const DROP_DOWN_DEPARTMENTS = "DROP_DOWN_DEPARTMENTS";

export const GET_PRODUCT_CATEGORY_BY_DEPARTMENT_ID = "GET_PRODUCT_CATEGORY_BY_DEPARTMENT_ID";

export const IS_STYLE_DEPARTMENT_DATA_LOADED = "IS_STYLE_DEPARTMENT_DATA_LOADED";
