export const GET_BUYER_PRODUCT_DEVELOPERS = "GET_BUYER_PRODUCT_DEVELOPERS";
export const GET_BUYER_PRODUCT_DEVELOPERS_BY_QUERY = "GET_BUYER_PRODUCT_DEVELOPERS_BY_QUERY";
export const GET_BUYER_PRODUCT_DEVELOPER_BY_ID = "GET_BUYER_PRODUCT_DEVELOPER_BY_ID";
export const ADD_BUYER_PRODUCT_DEVELOPER = "ADD_BUYER_PRODUCT_DEVELOPER";
export const UPDATE_BUYER_PRODUCT_DEVELOPER = "UPDATE_BUYER_PRODUCT_DEVELOPER";
export const DELETE_BUYER_PRODUCT_DEVELOPER = "DELETE_BUYER_PRODUCT_DEVELOPER";
export const DELETE_BUYER_PRODUCT_DEVELOPER_BY_RANGE = "DELETE_BUYER_PRODUCT_DEVELOPER_BY_RANGE";
export const SELECTED_BUYER_PRODUCT_DEVELOPER_NULL = "SELECTED_BUYER_PRODUCT_DEVELOPER_NULL";
export const OPEN_BUYER_PRODUCT_DEVELOPER_SIDEBAR = "OPEN_BUYER_PRODUCT_DEVELOPER_SIDEBAR";
export const OPEN_BUYER_PRODUCT_DEVELOPER_SIDEBAR_FOR_EDIT = "OPEN_BUYER_PRODUCT_DEVELOPER_SIDEBAR_FOR_EDIT";
export const DROP_DOWN_BUYER_PRODUCT_DEVELOPERS = "DROP_DOWN_BUYER_PRODUCT_DEVELOPERS";


export const PRODUCT_DEV_IMAGE_UPLOADING = "PRODUCT_DEV_IMAGE_UPLOADING";

export const BIND_PRODUCT_DEVELOPER_BASIC_INFO = "BIND_PRODUCT_DEVELOPER_BASIC_INFO";

export const IS_PRODUCT_DEVELOPER_DATA_LOADED = "IS_PRODUCT_DEVELOPER_DATA_LOADED";
