export const GET_PRODUCT_CATEGORIES = "GET_PRODUCT_CATEGORIES";
export const GET_PRODUCT_CATEGORIES_BY_QUERY = "GET_PRODUCT_CATEGORIES_BY_QUERY";
export const GET_PRODUCT_CATEGORY_BY_ID = "GET_PRODUCT_CATEGORY_BY_ID";
export const ADD_PRODUCT_CATEGORY = "ADD_PRODUCT_CATEGORY";
export const UPDATE_PRODUCT_CATEGORY = "UPDATE_PRODUCT_CATEGORY";
export const DELETE_PRODUCT_CATEGORY = "DELETE_PRODUCT_CATEGORY";
export const DELETE_STYLE_CATEGORY_FROM_PRODUCT_CATEGORY = "DELETE_STYLE_CATEGORY_FROM_PRODUCT_CATEGORY";
export const DELETE_PRODUCT_CATEGORY_BY_RANGE = "DELETE_PRODUCT_CATEGORY_BY_RANGE";

export const BIND_STYLE_PRODUCT_CATEGORY_DATA = "BIND_STYLE_PRODUCT_CATEGORY_DATA";


export const SELECTED_PRODUCT_CATEGORY_NULL = "SELECTED_PRODUCT_CATEGORY_NULL";
export const OPEN_PRODUCT_CATEGORY_SIDEBAR = "OPEN_PRODUCT_CATEGORY_SIDEBAR";
export const OPEN_PRODUCT_CATEGORY_SIDEBAR_FOR_EDIT = "OPEN_PRODUCT_CATEGORY_SIDEBAR_FOR_EDIT";
export const DROP_DOWN_PRODUCT_CATEGORIES = "DROP_DOWN_PRODUCT_CATEGORIES";
export const GET_STYLE_CATEGORY_BY_PRODUCT_CATEGORY_ID = "GET_STYLE_CATEGORY_BY_PRODUCT_CATEGORY_ID";

export const IS_STYLE_PRODUCT_CATEGORY_DATA_LOADED = "IS_STYLE_PRODUCT_CATEGORY_DATA_LOADED";
