export const GET_SEGMENT = "GET_SEGMENT";
export const GET_SEGMENT_BY_QUERY = "GET_SEGMENT_BY_QUERY";
export const GET_SEGMENT_BY_ID = "GET_SEGMENT_BY_ID";
export const ADD_SEGMENT = "ADD_SEGMENT";
export const UPDATE_SEGMENT = "UPDATE_SEGMENT";
export const DELETE_SEGMENT = "DELETE_SEGMENT";
export const DELETE_SEGMENT_BY_RANGE = "DELETE_SEGMENT_BY_RANGE";
export const SELECTED_SEGMENT_NULL = "SELECTED_SEGMENT_NULL";


export const OPEN_SEGMENT_SIDEBAR = "OPEN_SEGMENT_SIDEBAR";
export const OPEN_SEGMENT_SIDEBAR_FOR_EDIT = "OPEN_SEGMENT_SIDEBAR_FOR_EDIT";
export const DROP_DOWN_SEGMENT = "DROP_DOWN_SEGMENT";


export const GET_SEGMENT_VALUE_BY_SEGMENT_ID = "GET_SEGMENT_VALUE_BY_SEGMENT_ID";


export const GET_ITEM_GROUP_SEGMENTS_WITH_VALUE = "GET_ITEM_GROUP_SEGMENTS_WITH_VALUE";

export const IS_SEGMENT_DATA_LOADED = "IS_SEGMENT_DATA_LOADED";
export const IS_SEGMENT_DATA_ON_PROGRESS = "IS_SEGMENT_DATA_ON_PROGRESS";
export const IS_SEGMENT_DATA_SUBMIT_PROGRESS = "IS_SEGMENT_DATA_SUBMIT_PROGRESS";
