export const GET_ITEM_SEGMENT = "GET_ITEM_SEGMENT";
export const GET_ITEM_SEGMENT_BY_QUERY = "GET_ITEM_SEGMENT_BY_QUERY";
export const GET_ITEM_SEGMENT_BY_ID = "GET_ITEM_SEGMENT_BY_ID";
export const ADD_ITEM_SEGMENT = "ADD_ITEM_SEGMENT";
export const UPDATE_ITEM_SEGMENT = "UPDATE_ITEM_SEGMENT";
export const DELETE_ITEM_SEGMENT = "DELETE_ITEM_SEGMENT";
export const DELETE_ITEM_SEGMENT_BY_RANGE = "DELETE_ITEM_SEGMENT_BY_RANGE";
export const SELECTED_ITEM_SEGMENT_NULL = "SELECTED_ITEM_SEGMENT_NULL";


export const OPEN_ITEM_SEGMENT_SIDEBAR = "OPEN_ITEM_SEGMENT_SIDEBAR";
export const DROP_DOWN_ITEM_SEGMENTS = "DROP_DOWN_ITEM_SEGMENTS";


export const GET_ITEM_GROUP_SEGMENTS_WITH_VALUE = "GET_ITEM_GROUP_SEGMENTS_WITH_VALUE";
