
export const GET_DIVISIONS = "GET_DIVISIONS";
export const GET_DIVISIONS_BY_QUERY = "GET_DIVISIONS_BY_QUERY";
export const GET_DIVISION_BY_ID = "GET_DIVISIONS_BY_ID";
export const ADD_DIVISION = "ADD_DIVISION";
export const UPDATE_DIVISION = "UPDATE_DIVISION";
export const DELETE_DIVISION = "DELETE_DIVISION";
export const DELETE_DEPARTMENT_FROM_DIVISION = "DELETE_DEPARTMENT_FROM_DIVISION";
export const DELETE_DIVISIONS_BY_RANGE = "DELETE_DIVISIONS_BY_RANGE";
export const SELECTED_DIVISION_NULL = "SELECTED_DIVISION_NULL";

export const OPEN_DIVISION_SIDEBAR = "OPEN_DIVISION_SIDEBAR";
export const OPEN_DIVISION_SIDEBAR_FOR_EDIT = "OPEN_DIVISION_SIDEBAR_FOR_EDIT";
export const DROP_DOWN_DIVISIONS = "DROP_DOWN_DIVISIONS";

export const GET_DEPARTMENT_BY_DIVISION_ID = "GET_DEPARTMENT_BY_DIVISION_ID";

export const BIND_STYLE_DIVISION_DATA = "BIND_STYLE_DIVISION_DATA";

export const IS_STYLE_DIVISION_DATA_LOADED = "IS_STYLE_DIVISION_DATA_LOADED";
