
export const GET_BUYERS = 'GET_BUYERS';
export const GET_BUYERS_BY_QUERY = 'GET_BUYERS_BY_QUERY';
export const GET_BUYER_BY_ID = 'GET_BUYERS_BY_ID';

export const GET_BUYER_AGENT_BY_BUYER_ID = 'GET_BUYER_AGENT_BY_BUYER_ID';

export const GET_BUYER_PRODUCT_DEVELOPER_BY_BUYER_ID = 'GET_BUYER_PRODUCT_DEVELOPER_BY_BUYER_ID';
export const GET_BUYER_DEPARTMENT_BY_BUYER_ID = 'GET_BUYER_DEPARTMENT_BY_BUYER_ID';
export const GET_BUYER_SIZE_GROUPS_BY_BUYER_ID = 'GET_BUYER_SIZE_GROUPS_BY_BUYER_ID';
export const GET_BUYER_DROPDOWN_SIZE_GROUPS_BY_BUYER_ID = 'GET_BUYER_DROPDOWN_SIZE_GROUPS_BY_BUYER_ID';
export const GET_BUYER_COLOR_BY_BUYER_ID = 'GET_BUYER_COLOR_BY_BUYER_ID';
export const GET_BUYER_DROPDOWN_COLOR_BY_BUYER_ID = 'GET_BUYER_DROPDOWN_COLOR_BY_BUYER_ID';
export const ADD_BUYER = 'ADD_BUYER';
export const UPDATE_BUYER = 'UPDATE_BUYER';
export const DELETE_BUYER = 'DELETE_BUYER';
export const DELETE_BUYERS_BY_RANGE = 'DELETE_BUYERS_BY_RANGE';
export const SELECTED_BUYER_NULL = 'SELECTED_BUYER_NULL';

export const OPEN_BUYER_SIDEBER = 'OPEN_BUYER_SIDEBER';
export const DROP_DOWN_BUYERS = 'DROP_DOWN_BUYERS';
export const IS_ASSIGN_AGENT = 'IS_ASSIGN_AGENT';
export const IS_ASSIGN_PRODUCT_DEVELOPER = 'IS_ASSIGN_PRODUCT_DEVELOPER';

export const BIND_BUYER_BASIC_INFO = "BIND_BUYER_BASIC_INFO";

export const BUYER_STYLE_DROPDOWN = 'BUYER_STYLE_DROPDOWN';


export const CLEAR_ALL_BUYER_STATE = "CLEAR_ALL_BUYER_STATE";


export const BUYER_IMAGE_UPLOAD_LOADING = "BUYER_IMAGE_UPLOAD_LOADING";
export const BUYER_IMAGE_UPLOAD = "BUYER_IMAGE_UPLOAD";


export const IS_BUYER_DATA_LOADED = "IS_BUYER_DATA_LOADED";
export const IS_BUYER_DATA_ON_PROGRESS = "IS_BUYER_DATA_ON_PROGRESS";
export const IS_BUYER_DATA_SUBMIT_PROGRESS = "IS_BUYER_DATA_SUBMIT_PROGRESS";
