export const GET_ITEM_SEGMENT_VALUE = "GET_ITEM_SEGMENT_VALUE";
export const GET_ITEM_SEGMENT_VALUE_BY_QUERY = "GET_ITEM_SEGMENT_VALUE_BY_QUERY";
export const GET_ITEM_SEGMENT_VALUE_BY_ID = "GET_ITEM_SEGMENT_VALUE_BY_ID";
export const ADD_ITEM_SEGMENT_VALUE = "ADD_ITEM_SEGMENT_VALUE";
export const UPDATE_ITEM_SEGMENT_VALUE = "UPDATE_ITEM_SEGMENT_VALUE";
export const DELETE_ITEM_SEGMENT_VALUE = "DELETE_ITEM_SEGMENT_VALUE";
export const DELETE_ITEM_SEGMENT_VALUE_BY_RANGE = "DELETE_ITEM_SEGMENT_VALUE_BY_RANGE";
export const SELECTED_ITEM_SEGMENT_VALUE_NULL = "SELECTED_ITEM_SEGMENT_VALUE_NULL";


export const OPEN_ITEM_SEGMENT_VALUE_SIDEBAR = "OPEN_ITEM_SEGMENT_VALUE_SIDEBAR";
export const DROP_DOWN_ITEM_SEGMENT_VALUES = "DROP_DOWN_ITEM_SEGMENT_VALUES";

