export const GET_VENDOR_GROUPS_BY_QUERY = 'GET_VENDOR_GROUPS_BY_QUERY';
export const GET_VENDOR_GROUP_BY_ID = 'GET_VENDOR_GROUP_BY_ID';
export const GET_VENDOR_GROUP_DROPDOWN = 'GET_VENDOR_GROUP_DROPDOWN';
export const GET_VENDOR_SUB_GROUPS_DROPDOWN_BY_VENDOR_ID = 'GET_VENDOR_SUB_GROUPS_DROPDOWN_BY_VENDOR_ID';


export const ADD_VENDOR_GROUP = "ADD_VENDOR_GROUP";
export const UPDATE_VENDOR_GROUP = "UPDATE_VENDOR_GROUP";

export const ADD_VENDOR_SUB_GROUP = "ADD_VENDOR_SUB_GROUP";
export const UPDATE_VENDOR_SUB_GROUP = "UPDATE_VENDOR_SUB_GROUP";


export const GET_VENDOR_SUB_GROUP_VENDOR_GROUP_BY_ID = 'GET_VENDOR_SUB_GROUP_VENDOR_GROUP_BY_ID';


export const OPEN_VENDOR_GROUPS_SIDEBAR = "OPEN_VENDOR_GROUPS_SIDEBAR";
export const OPEN_VENDOR_GROUPS_EDIT_SIDEBAR = "OPEN_VENDOR_GROUPS_EDIT_SIDEBAR";

export const OPEN_VENDOR_SUB_GROUPS_SIDEBAR = "OPEN_VENDOR_SUB_GROUPS_SIDEBAR";


export const BIND_VENDOR_GROUP_BASIC_INFO = "BIND_VENDOR_GROUP_BASIC_INFO";
