
export const GET_DESTINATIONS = "GET_DESTINATIONS";
export const GET_DESTINATIONS_BY_QUERY = "GET_DESTINATIONS_BY_QUERY";
export const GET_DESTINATION_BY_ID = "GET_DESTINATION_BY_ID";
export const ADD_DESTINATION = "ADD_DESTINATION";
export const UPDATE_DESTINATION = "UPDATE_DESTINATION";
export const DELETE_DESTINATION = "DELETE_DESTINATION";
export const DELETE_DESTINATIONS_BY_RANGE = "DELETE_DESTINATIONS_BY_RANGE";

export const BIND_DESTINATION_DATA = "BIND_DESTINATION_DATA";

export const SELECTED_DESTINATION_NULL = "SELECTED_DESTINATION_NULL";


export const OPEN_DESTINATION_SIDEBAR = "OPEN_DESTINATION_SIDEBAR";
export const OPEN_DESTINATION_SIDEBAR_FOR_EDIT = "OPEN_DESTINATION_SIDEBAR_FOR_EDIT";
export const DROP_DOWN_DESTINATIONS = "DROP_DOWN_DESTINATIONS";

export const GET_STYLE_DESTINATIONS_DROP_DOWN = "GET_STYLE_DESTINATIONS_DROP_DOWN";

export const GET_DESTINATION_BY_COUNTRY_NAME = "GET_DESTINATION_BY_COUNTRY_NAME";

export const GET_DESTINATION_BY_BUYER_ID = "GET_DESTINATION_BY_BUYER_ID";


export const GET_DESTINATIONS_BY_DESTINATION_GROUP_ID = "GET_DESTINATIONS_BY_DESTINATION_GROUP_ID";
export const IS_DESTINATION_DATA_LOADED = "IS_DESTINATION_DATA_LOADED";
export const IS_DESTINATION_DATA_ON_PROGRESS = "IS_DESTINATION_DATA_ON_PROGRESS";
export const IS_DESTINATION_DATA_SUBMIT_PROGRESS = "IS_DESTINATION_DATA_SUBMIT_PROGRESS";
