export const GET_PI_BY_QUERY = "GET_PI_BY_QUERY";
export const GET_PI_BY_ID = "GET_PI_BY_ID";
export const ADD_PI_INVOICE = "ADD_PI_INVOICE";
export const UPDATE_PI_INVOICE = "UPDATE_PI_INVOICE";

export const GET_SUPPLIER_ORDERS = "GET_SUPPLIER_ORDERS";
export const GET_PROCUREMENT_ITEMS = "GET_PROCUREMENT_ITEMS";

export const BIND_PI_BASIC_INFO = "BIND_PI_BASIC_INFO";

export const BIND_SELECTED_SUPPLIER_ORDERS = "BIND_SELECTED_SUPPLIER_ORDERS";
export const BIND_SELECTED_PROCUREMENT_ITEMS = "BIND_SELECTED_PROCUREMENT_ITEMS";

export const GET_DATA_FROM_IPO_FOR_IPI = "GET_DATA_FROM_IPO_FOR_IPI";

export const IS_FILE_UPLOADED_COMPLETE = "IS_FILE_UPLOADED_COMPLETE";

export const IS_PI_DATA_LOADED = "IS_PI_DATA_LOADED";
export const IS_PI_DATA_PROGRESS = "IS_PI_DATA_PROGRESS";

export const DELETE_PI = "DELETE_PI";

export const CLEAR_ALL_PI_STATE = "CLEAR_ALL_PI_STATE";