export const GET_ITEM_GROUPS = "GET_ITEM_GROUPS";
export const GET_ITEM_GROUPS_BY_QUERY = "GET_ITEM_GROUPS_BY_QUERY";
export const GET_ITEM_GROUP_BY_ID = "GET_ITEM_GROUP_BY_ID";
export const ADD_ITEM_GROUP = "ADD_ITEM_GROUP";
export const UPDATE_ITEM_GROUP = "UPDATE_ITEM_GROUP";
export const DELETE_ITEM_GROUP = "DELETE_ITEM_GROUP";
export const DELETE_ITEM_GROUP_BY_RANGE = "DELETE_ITEM_GROUP_BY_RANGE";
export const SELECTED_ITEM_GROUP_NULL = "SELECTED_ITEM_GROUP_NULL";


export const OPEN_ITEM_GROUP_SIDEBAR = "OPEN_ITEM_GROUP_SIDEBAR";
export const OPEN_ITEM_GROUP_SIDEBAR_FOR_EDIT = "OPEN_ITEM_GROUP_SIDEBAR_FOR_EDIT";
export const DROP_DOWN_ITEM_GROUPS = "DROP_DOWN_ITEM_GROUPS";
export const DROP_DOWN_CATEGORY_GROUPS = "DROP_DOWN_CATEGORY_GROUPS";

export const OPEN_ASSIGN_SUB_CATEGORY_MODAL = "OPEN_ASSIGN_SUB_CATEGORY_MODAL";
export const GET_ITEM_SUB_GROUP_BY_ITEM_GROUP_ID = "GET_ITEM_SUB_GROUP_BY_ITEM_GROUP_ID";
export const OPEN_ASSIGN_ITEM_SEGMENT_MODAL = "OPEN_ASSIGN_ITEM_SEGMENT_MODAL";
export const GET_ITEM_SEGMENT_BY_ITEM_GROUP_ID = "GET_ITEM_SUB_GROUP_BY_ITEM_ID";

export const OPEN_ASSIGN_ITEM_SEGMENT_VALUE_MODAL = "OPEN_ASSIGN_ITEM_SEGMENT_VALUE_MODAL";
export const GET_ITEM_SEGMENT_VALUE_BY_ITEM_GROUP_ID = "GET_ITEM_SEGMENT_VALUE_BY_ITEM_GROUP_ID";
export const GET_ITEM_SEGMENT_DROPDOWN_BY_ITEM_GROUP_ID = "GET_ITEM_SEGMENT_DROPDOWN_BY_ITEM_GROUP_ID";
export const GET_ITEM_SUB_GROUP_DROPDOWN_BY_ITEM_GROUP_ID = "GET_ITEM_SUB_GROUP_DROPDOWN_BY_ITEM_GROUP_ID";
export const GET_ITEM_SUB_GROUP_SEGMENT_BY_ITEM_GROUP_ID = "GET_ITEM_SUB_GROUP_SEGMENT_BY_ITEM_GROUP_ID";

export const GET_ITEM_GROUPS_DROPDOWN_BY_GROUP = "GET_ITEM_GROUPS_DROPDOWN_BY_GROUP";
export const GET_ITEM_FABRIC_GROUPS_DROPDOWN_BY_GROUP = "GET_ITEM_FABRIC_GROUPS_DROPDOWN_BY_GROUP";
export const GET_ITEM_TRIM_GROUPS_DROPDOWN_BY_GROUP = "GET_ITEM_TRIM_GROUPS_DROPDOWN_BY_GROUP";
export const GET_ITEM_PACK_GROUPS_DROPDOWN_BY_GROUP = "GET_ITEM_PACK_GROUPS_DROPDOWN_BY_GROUP";


export const IS_ITEM_GROUP_DATA_LOADED = "IS_ITEM_GROUP_DATA_LOADED";
export const IS_ITEM_GROUP_ON_PROGRESS = "IS_ITEM_GROUP_ON_PROGRESS";
export const IS_ITEM_GROUP_DATA_SUBMIT_PROGRESS = "IS_ITEM_GROUP_DATA_SUBMIT_PROGRESS";
