export const GET_PROCUREMENTS_BY_QUERY = 'GET_PROCUREMENTS_BY_QUERY';
export const GET_PROCUREMENT_BY_ID = "GET_PROCUREMENT_BY_ID";
export const BIND_SELECTED_ITEMS_FOR_PROCUREMENT = 'BIND_SELECTED_ITEMS_FOR_PROCUREMENT';
export const BIND_PROCUREMENT_BASIC_INFO = "BIND_PROCUREMENT_BASIC_INFO";

export const BIND_ITEM_DETAILS_WITH_MIN_ORDER = "BIND_ITEM_DETAILS_WITH_MIN_ORDER";

export const GET_PROCUREMENT_DROP_DOWN = "GET_PROCUREMENT_DROP_DOWN";


export const BIND_PROCUREMENT_ITEMS = "BIND_PROCUREMENT_ITEMS";

export const DELETE_PROCUREMENT = "DELETE_PROCUREMENT";

export const IS_PROCUREMENT_DATA_LOADED = "IS_PROCUREMENT_DATA_LOADED";

export const CLEAR_PROCUREMENT_ALL_STATE = "CLEAR_PROCUREMENT_ALL_STATE";