export const GET_WAREHOUSES = "GET_WAREHOUSES";
export const GET_WAREHOUSE_BY_QUERY = "GET_WAREHOUSE_BY_QUERY";
export const GET_WAREHOUSE_BY_ID = "GET_WAREHOUSE_BY_ID";
export const GET_WAREHOUSE_DROPDOWN = "GET_WAREHOUSE_DROPDOWN";
export const ADD_WAREHOUSE = "ADD_WAREHOUSE";
export const UPDATE_WAREHOUSE = "UPDATE_WAREHOUSE";
export const BIND_WAREHOUSE_DATA_ONCHANGE = "BIND_WAREHOUSE_DATA_ONCHANGE";

export const IS_WAREHOUSE_DATA_LOADED = "IS_WAREHOUSE_DATA_LOADED";
export const IS_WAREHOUSE_ON_PROGRESS = "IS_WAREHOUSE_ON_PROGRESS";
