
export const GET_SINGLE_STYLES = 'GET_SINGLE_STYLES';
export const GET_SINGLE_STYLES_BY_QUERY = 'GET_SINGLE_STYLES_BY_QUERY';
export const GET_SINGLE_STYLE_BY_ID = 'GET_SINGLE_STYLES_BY_ID';
export const ADD_SINGLE_STYLE = 'ADD_SINGLE_STYLE';
export const UPDATE_SINGLE_STYLE = 'UPDATE_SINGLE_STYLE';
export const DELETE_SINGLE_STYLE = 'DELETE_SINGLE_STYLE';
export const DELETE_SINGLE_STYLES_BY_RANGE = 'DELETE_SINGLE_STYLES_BY_RANGE';
export const SELECTED_SINGLE_STYLE_NULL = 'SELECTED_SINGLE_STYLE_NULL';


export const OPEN_SINGLE_STYLE_SIDEBER = 'OPEN_SINGLE_STYLE_SIDEBER';
export const OPEN_SINGLE_STYLE_FORM = 'OPEN_SINGLE_STYLE_FORM';

export const DROP_DOWN_SINGLE_STYLES = 'DROP_DOWN_SINGLE_STYLES';

export const UPLOAD_SINGLE_STYLE_IMAGE = 'UPLOAD_SINGLE_STYLE_IMAGE';
export const GET_SINGLE_STYLE_UPLOAD_IMAGE = 'GET_SINGLE_STYLE_UPLOAD_IMAGE';
export const GET_SINGLE_STYLE_UPLOAD_FILE = 'GET_SINGLE_STYLE_UPLOAD_FILE';
export const IS_FILE_UPLOADED_COMPLETE = 'IS_FILE_UPLOADED_COMPLETE';
export const IS_PHOTO_UPLOADED_COMPLETE = 'IS_PHOTO_UPLOADED_COMPLETE';
export const DELETE_SINGLE_STYLE_FILE = 'DELETE_SINGLE_STYLE_FILE';

export const GET_SINGLE_STYLE_COLORS = 'GET_SINGLE_STYLE_COLORS';
export const GET_SINGLE_STYLE_SIZES = 'GET_SINGLE_STYLE_SIZES';
export const GET_SINGLE_STYLE_SIZE_GROUPS = 'GET_SINGLE_STYLE_SIZE_GROUPS';

export const GET_SINGLE_TEMPLATE_DROPDOWN = 'GET_SINGLE_TEMPLATE_DROPDOWN';

export const SINGLE_STYLE_FILE_DOWNLOAD = 'SINGLE_STYLE_FILE_DOWNLOAD';

export const SINGLE_STYLE_DATA_BIND = 'SINGLE_STYLE_DATA_BIND';

export const CLEAR_ALL_SINGLE_STYLE_STATE = 'CLEAR_ALL_SINGLE_STYLE_STATE';

export const IS_SINGLE_STYLE_DATA_LOADED = 'IS_SINGLE_STYLE_DATA_LOADED';

export const IS_SINGLE_STYLE_DATA_PROGRESS = "IS_SINGLE_STYLE_DATA_PROGRESS";
export const IS_SINGLE_STYLE_DATA_SUBMIT_PROGRESS = "IS_SINGLE_STYLE_DATA_SUBMIT_PROGRESS";
