
export const GET_CONSUMPTIONS = "GET_CONSUMPTIONS";
export const GET_CONSUMPTIONS_BY_QUERY = "GET_CONSUMPTIONS_BY_QUERY";
export const GET_CONSUMPTION_BY_ID = "GET_CONSUMPTIONS_BY_ID";
export const GET_SET_CONSUMPTION_BY_ID = "GET_SET_CONSUMPTION_BY_ID";
export const GET_PACK_CONSUMPTION_BY_ID = "GET_PACK_CONSUMPTION_BY_ID";

export const ADD_CONSUMPTION = "ADD_CONSUMPTION";
export const UPDATE_CONSUMPTION = "UPDATE_CONSUMPTION";
export const DELETE_CONSUMPTION = "DELETE_CONSUMPTION";
export const DELETE_CONSUMPTIONS_BY_RANGE = "DELETE_CONSUMPTIONS_BY_RANGE";

export const DELETE_CONSUMPTION_ORDER_DETAILS = "DELETE_CONSUMPTION_ORDER_DETAILS";

export const SELECTED_CONSUMPTION_NULL = "SELECTED_CONSUMPTION_NULL";
export const DROP_DOWN_CONSUMPTIONS = 'DROP_DOWN_CONSUMPTIONS';

export const GET_CONSUMPTION_BASIC_INFO = "GET_CONSUMPTION_BASIC_INFO";
export const GET_CONSUMPTION_FABRIC_DETAILS = "GET_CONSUMPTION_FABRIC_DETAILS";
export const GET_CONSUMPTION_ACCESSORIES_DETAILS = "GET_CONSUMPTION_ACCESSORIES_DETAILS";
export const GET_COSTING_HISTORY_FOR_CONSUMPTION = "GET_COSTING_HISTORY_FOR_CONSUMPTION";
export const GET_ITEM_SUB_GROUP_FOR_CONSUMPTION = "GET_ITEM_SUB_GROUP_FOR_CONSUMPTION";
export const GET_CONSUMPTION_DETAILS_COLOR_SIZE_SENSE = "GET_CONSUMPTION_DETAILS_COLOR_SIZE_SENSE";

export const GET_CONSUMPTION_ORDER_DERAILS = "GET_CONSUMPTION_ORDER_DERAILS";

export const GET_CONSUMPTION_STYLE_PURCHASE_ORDER_DETAILS = "GET_CONSUMPTION_STYLE_PURCHASE_ORDER_DETAILS";
export const GET_SET_CONSUMPTION_STYLE_PURCHASE_ORDER_DETAILS = "GET_SET_CONSUMPTION_STYLE_PURCHASE_ORDER_DETAILS";

export const GET_CONSUMPTION_PURCHASE_ORDER_COLORS = "GET_CONSUMPTION_PURCHASE_ORDER_COLORS";
export const GET_CONSUMPTION_PURCHASE_ORDER_SIZES = "GET_CONSUMPTION_PURCHASE_ORDER_SIZES";

export const GET_CONSUMPTION_COSTING_DETAILS = "GET_CONSUMPTION_COSTING_DETAILS";

export const GET_CONSUMPTION_PACKAGING_ACCESSORIES_DETAILS = "GET_CONSUMPTION_PACKAGING_ACCESSORIES_DETAILS";

export const IS_CONSUMPTION_DATA_LOADED = "IS_CONSUMPTION_DATA_LOADEDs";

export const CLEAN_CONSUMPTION_ALL_STATE = "CLEAN_CONSUMPTION_ALL_STATE";

export const CLONE_CONSUMPTION = "CLONE_CONSUMPTION";

export const SIZE_COLOR_SENSE_DATA_ON_PROGRESS = "SIZE_COLOR_SENSE_DATA_ON_PROGRESS";

export const CONSUMPTION_PURCHASE_ORDER_DATA_ON_PROGRESS = "CONSUMPTION_PURCHASE_ORDER_DATA_ON_PROGRESS";