
export const GET_ROLES_BY_QUERY = "GET_ROLES_BY_QUERY";
export const GET_ROLE_BY_ID = "GET_ROLE_BY_ID";
export const GET_ROLE_PERMISSION_BY_ROLE_ID = "GET_ROLE_PERMISSION_BY_ROLE_ID";
export const ADD_ROLE = "ADD_ROLE";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const DELETE_ROLE = "DELETE_ROLE";

export const BIND_ROLE_PERMISSIONS = "BIND_ROLE_PERMISSIONS";

export const IS_ROLE_DATA_LOADED = "IS_ROLE_DATA_LOADED";

export const IS_ROLE_DATA_PROGRESS = "IS_ROLE_DATA_PROGRESS";
export const IS_ROLE_DATA_SUBMIT_PROGRESS = "IS_ROLE_DATA_SUBMIT_PROGRESS";

export const GET_ROLE_PERMISSIONS_BY_ROLE_ID = "GET_ROLE_PERMISSIONS_BY_ROLE_ID";

export const IS_ROLE_ADD_FORM_SIDEBAR_OPEN = "IS_ROLE_ADD_FORM_SIDEBAR_OPEN";
export const IS_ROLE_EDIT_FORM_SIDEBAR_OPEN = "IS_ROLE_EDIT_FORM_SIDEBAR_OPEN";

export const IS_ROLE_PERMISSION_MODAL_OPEN = "IS_ROLE_PERMISSION_MODAL_OPEN";

export const BIND_ROLE_BASIC_INFO = "BIND_ROLE_BASIC_INFO";

export const GET_ROLES_DROPDOWN = "GET_ROLES_DROPDOWN";


export const CLEAR_ROLE_ALL_STATE = "CLEAR_ROLE_ALL_STATE";
