
export const GET_SINGLE_PACKAGING = "GET_SINGLE_PACKAGING";
export const GET_SINGLE_PACKAGING_BY_QUERY = "GET_SINGLE_PACKAGING_BY_QUERY";
export const GET_SINGLE_PACKAGING_BY_ID = "GET_SINGLE_PACKAGING_BY_ID";
export const GET_SINGLE_PACKAGING_DETAILS_BY_ID = "GET_SINGLE_PACKAGING_DETAILS_BY_ID";
export const ADD_SINGLE_PACKAGING = "ADD_SINGLE_PACKAGING";
export const UPDATE_SINGLE_PACKAGING = "UPDATE_SINGLE_PACKAGING";
export const DELETE_SINGLE_PACKAGING = "DELETE_SINGLE_PACKAGING";
export const DELETE_SINGLE_PACKAGING_BY_RANGE = "DELETE_SINGLE_PACKAGING_BY_RANGE";
export const SINGLE_PACKAGING_ACCESSORIES_DETAILS = 'SINGLE_PACKAGING_ACCESSORIES_DETAILS';

export const BIND_SINGLE_PACKAGING_BASIC_INFO = "BIND_SINGLE_PACKAGING_BASIC_INFO";
export const BIND_SINGLE_PACKAGING_COLOR_SIZE_DETAILS = "BIND_SINGLE_PACKAGING_COLOR_SIZE_DETAILS";
export const GET_SINGLE_PACKAGING_DETAILS = "GET_SINGLE_PACKAGING_DETAILS";


export const GET_SET_PACKAGING = "GET_SET_PACKAGING";
export const GET_SET_PACKAGING_BY_QUERY = "GET_SET_PACKAGING_BY_QUERY";

export const GET_SET_PACKAGING_BY_ID = "GET_SET_PACKAGING_BY_ID";
export const GET_SET_PACKAGING_DETAILS = "GET_SET_PACKAGING_DETAILS";

export const BIND_SET_PACKAGING_BASIC_INFO = "BIND_SET_PACKAGING_BASIC_INFO";

export const ADD_SET_PACKAGING = "ADD_SET_PACKAGING";
export const UPDATE_SET_PACKAGING = "UPDATE_SET_PACKAGING";
export const DELETE_SET_PACKAGING = "DELETE_SET_PACKAGING";
export const DELETE_SET_PACKAGING_BY_RANGE = "DELETE_SET_PACKAGING_BY_RANGE";
export const SET_PACKAGING_ACCESSORIES_DETAILS = 'SET_PACKAGING_ACCESSORIES_DETAILS';
export const BIND_SET_PACKAGING_STYLE_SIZE_DETAILS = "BIND_SET_PACKAGING_STYLE_SIZE_DETAILS";


export const GET_PACKAGING_SIZE_COLOR_DROPDOWN = "GET_PACKAGING_SIZE_COLOR_DROPDOWN";

export const GET_PACKAGING_SIZE_DROPDOWN = "GET_PACKAGING_SIZE_DROPDOWN";
export const GET_PACKAGING_COLOR_DROPDOWN = "GET_PACKAGING_COLOR_DROPDOWN";

export const GET_PACKAGING_PURCHASER_ORDERS = "GET_PACKAGING_PURCHASER_ORDERS";

export const CLEAR_PACKAGING_ALL_STATE = "CLEAR_PACKAGING_ALL_STATE";


export const GET_UOM_DROPDOWN_BY_UOM_SET_NAME = "GET_UOM_DROPDOWN_BY_UOM_SET_NAME";
