export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_AUTHENTICATE_USER = 'GET_AUTHENTICATE_USER';
export const GET_AUTHENTICATE_USER_PERMISSION = 'GET_AUTHENTICATE_USER_PERMISSION';

export const IS_USER_LOGGED_IN = 'IS_USER_LOGGED_IN';

export const AUTH_TOKEN_STORE = 'AUTH_TOKEN_STORE';


export const FILE_PROGRESS = 'FILE_PROGRESS';

export const GET_PROGRESS = "GET_PROGRESS";
export const POST_PROGRESS = "POST_PROGRESS";


export const BIND_AUTH_NAVIGATION = "BIND_AUTH_NAVIGATION";