export const consumptionBasicInfoModel = {
    buyer: null,
    buyerId: '',
    buyerName: '',
    order: null,
    orderId: '',
    orderNumber: '',
    style: null,
    styleId: '',
    styleNumber: '',
    isSetStyle: false,
    costing: null,
    costingId: '',
    consumptionNumber: '',
    isConsumptionNumberInput: false,
    styleOrderDetails: [],
    packOrderDetails: [],
    isClone: false,
    dataAlreadyLoaded: false
};