export const GET_UNIT_SET = "GET_UNIT_SET";
export const GET_UNIT_SETS_BY_QUERY = "GET_UNIT_SETS_BY_QUERY";
export const GET_UNIT_SET_BY_ID = "GET_UNIT_SET_BY_ID";
export const ADD_UNIT_SET = "ADD_UNIT_SET";
export const UPDATE_UNIT_SET = "UPDATE_UNIT_SET";
export const UPDATE_UNIT_SET_UNIT = "UPDATE_UNIT_SET_UNIT";
export const DELETE_UNIT_SET = "DELETE_UNIT_SET";
export const DELETE_UNIT_SETS_BY_RANGE = "DELETE_UNIT_SETS_BY_RANGE";
export const SELECTED_UNIT_SET_NULL = "SELECTED_UNIT_SET_NULL";


export const OPEN_UNIT_SET_SIDEBAR = "OPEN_UNIT_SET_SIDEBAR";
export const OPEN_UNIT_SET_SIDEBAR_FOR_EDIT = "OPEN_UNIT_SET_SIDEBAR_FOR_EDIT";
export const DROP_DOWN_UNIT_SETS = "DROP_DOWN_UNIT_SETS";

export const UNIT_SETS_UNITS = "UNIT_SETS_UNITS";
export const GET_UNIT_SETS_UNIT_BY_ID = "GET_UNIT_SETS_UNIT_BY_ID";

export const GET_ORDER_AND_CONSUMPTION_UOM_DROPDOWN_BY_ITEM_GROUP_ID = "GET_ORDER_AND_CONSUMPTION_UOM_DROPDOWN_BY_ITEM_GROUP_ID";

export const GET_DEFAULT_UOM_DROPDOWN = "GET_DEFAULT_UOM_DROPDOWN";

export const GET_UOM_DROPDOWN_BY_UOM_SET_ID = "GET_UOM_DROPDOWN_BY_UOM_SET_ID";

export const GET_UOM_DROPDOWN_BY_UOM_SET_NAME = "GET_UOM_DROPDOWN_BY_UOM_SET_NAME";
