
export const GET_COSTING_GROUPS = "GET_COSTING_GROUPS";
export const GET_COSTING_GROUPS_BY_QUERY = "GET_COSTING_GROUPS_BY_QUERY";
export const GET_COSTING_GROUP_BY_ID = "GET_COSTING_GROUP_BY_ID";
export const ADD_COSTING_GROUP = "ADD_COSTING_GROUP";
export const UPDATE_COSTING_GROUP = "UPDATE_COSTING_GROUP";
export const DELETE_COSTING_GROUP = "DELETE_COSTING_GROUP";
export const DELETE_COSTING_GROUPS_BY_RANGE = "DELETE_COSTING_GROUPS_BY_RANGE";
export const SELECTED_COSTING_GROUP_NULL = "SELECTED_COSTING_GROUP_NULL";

export const OPEN_COSTING_GROUP_SIDEBAR = "OPEN_COSTING_GROUP_SIDEBAR";
export const OPEN_COSTING_GROUP_SIDEBAR_FOR_EDIT = "OPEN_COSTING_GROUP_SIDEBAR_FOR_EDIT";
export const DROP_DOWN_COSTING_GROUPS = "DROP_DOWN_COSTING_GROUPS";
