
export const GET_SET_STYLES = 'GET_SET_STYLES';
export const GET_SET_STYLES_BY_QUERY = 'GET_SET_STYLES_BY_QUERY';
export const GET_SET_STYLE_BY_ID = 'GET_SET_STYLES_BY_ID';
export const ADD_SET_STYLE = 'ADD_SINGLE_SET';
export const UPDATE_SET_STYLE = 'UPDATE_SET_STYLE';
export const DELETE_SET_STYLE = 'DELETE_SET_STYLE';
export const DELETE_SET_STYLES_BY_RANGE = 'DELETE_SET_STYLES_BY_RANGE';
export const SELECTED_SET_STYLE_NULL = 'SELECTED_SET_STYLE_NULL';

export const SET_STYLE_DETAILS_UPDATE = 'SET_STYLE_DETAILS_UPDATE';


export const OPEN_SET_STYLE_SIDEBER = 'OPEN_SET_STYLE_SIDEBER';
export const OPEN_SET_STYLE_FORM = 'OPEN_SET_STYLE_FORM';

export const DROP_DOWN_SET_STYLES = 'DROP_DOWN_SET_STYLES';
export const DROP_DOWN_STYLE_SIZES = 'DROP_DOWN_STYLE_SIZES';

export const GET_SET_STYLES_SIZE_GROUPS = 'GET_SET_STYLES_SIZE_GROUPS';
export const GET_SET_STYLES_COLORS = 'GET_SET_STYLES_COLORS';


export const UPLOAD_SET_STYLE_IMAGE = 'UPLOAD_SET_STYLE_IMAGE';
export const GET_SET_STYLE_UPLOAD_IMAGE = 'GET_SET_STYLE_UPLOAD_IMAGE';
export const GET_SET_STYLE_UPLOAD_FILE = 'GET_SET_STYLE_UPLOAD_FILE';
export const IS_SET_FILE_UPLOADED_COMPLETE = 'IS_SET_FILE_UPLOADED_COMPLETE';
export const IS_SET_PHOTO_UPLOADED_COMPLETE = 'IS_SET_PHOTO_UPLOADED_COMPLETE';
export const DELETE_SET_STYLE_PHOTO = 'DELETE_SET_STYLE_PHOTO';
export const DELETE_SET_STYLE_FILE = 'DELETE_SET_STYLE_FILE';

export const GET_SET_STYLE_STYLES_BY_SET_STYLE_ID = 'GET_SET_STYLE_STYLES_BY_SET_STYLE_ID';

export const SET_STYLE_DATA_BIND = 'SET_STYLE_DATA_BIND';


export const CLEAR_ALL_SET_STYLE_STATE = 'CLEAR_ALL_SET_STYLE_STATE';

export const IS_SET_STYLE_DATA_LOADED = 'IS_SET_STYLE_DATA_LOADED';
