export const GET_ITEM = "GET_ITEM";
export const GET_ITEMS_BY_QUERY = "GET_ITEMS_BY_QUERY";
export const GET_ITEM_BY_ID = "GET_ITEM_BY_ID";
export const ADD_ITEM = "ADD_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const DELETE_ITEMS_BY_RANGE = "DELETE_ITEMS_BY_RANGE";
export const SELECTED_ITEM_NULL = "SELECTED_ITEM_NULL";
export const GET_ITEM_DESCRIPTION_DROPDOWN = "GET_ITEM_DESCRIPTION_DROPDOWN";

export const OPEN_ITEM_SIDEBAR = "OPEN_ITEM_SIDEBAR";
export const OPEN_ITEM_SIDEBAR_FOR_EDIT = "OPEN_ITEM_SIDEBAR_FOR_EDIT";
export const DROP_DOWN_ITEMS = "DROP_DOWN_ITEMS";
export const GET_DROP_DOWN_ITEMS = "GET_DROP_DOWN_ITEMS";

export const GET_ITEMS_DROPDOWN_BY_ITEM_GROUP = "GET_ITEMS_DROPDOWN_BY_ITEM_GROUP";

export const BIND_ITEM_BASIC_INFO = "BIND_ITEM_BASIC_INFO";


export const IS_ITEM_DATA_LOADED = "IS_ITEM_DATA_LOADED";
export const IS_ITEM_DATA_ON_PROGRESS = "IS_ITEM_DATA_ON_PROGRESS";
export const IS_ITEM_DATA_SUBMIT_PROGRESS = "IS_ITEM_DATA_SUBMIT_PROGRESS";
