export const GET_BOMS = "GET_BOMS";
export const GET_BOMS_BY_QUERY = "GET_BOMS_BY_QUERY";
export const GET_BOM_BY_ID = "GET_BOM_BY_ID";
export const ADD_BOM = "ADD_BOM";
export const UPDATE_BOM = "UPDATE_BOM";
export const DELETE_BOM = "DELETE_BOM";
export const DELETE_BOM_BY_RANGE = "DELETE_BOM_BY_RANGE";
export const OPEN_BOM_VIEW_MODAL = "OPEN_BOM_VIEW_MODAL";
export const SELECTED_BOM_NULL = "SELECTED_BOM_NULL";
export const DROP_DOWN_BOMS = "DROP_DOWN_BOMS";

export const BIND_BOM_BASIC_INFO = "BIND_BOM_BASIC_INFO";

export const GET_BOM_GENERATION_DETAILS = "GET_BOM_GENERATION_DETAILS";

export const GET_BOM_PURCHASE_ORDERS = "GET_BOM_PURCHASE_ORDERS";

export const GET_BOMS_BY_ORDER_IDS = "GET_BOMS_BY_ORDER_IDS";

export const CLEAR_ALL_BOM_STATE = "CLEAR_ALL_BOM_STATE";

export const BOM_PURCHASE_ORDER_DATA_ON_PROGRESS = "BOM_PURCHASE_ORDER_DATA_ON_PROGRESS";

export const BOM_ITEM_DETAILS_DATA_ON_PROGRESS = "BOM_ITEM_DETAILS_DATA_ON_PROGRESS";