export const GET_SAMPLE_ASSIGNEES = "GET_SAMPLE_ASSIGNEES";
export const GET_SAMPLE_ASSIGNEES_BY_QUERY = "GET_SAMPLE_ASSIGNEES_BY_QUERY";
export const GET_SAMPLE_ASSIGNEE_BY_ID = "GET_SAMPLE_ASSIGNEE_BY_ID";
export const ADD_SAMPLE_ASSIGNEE = "ADD_SAMPLE_ASSIGNEE";
export const UPDATE_SAMPLE_ASSIGNEE = "UPDATE_SAMPLE_ASSIGNEE";
export const DELETE_SAMPLE_ASSIGNEE = "DELETE_SAMPLE_ASSIGNEE";
export const DELETE_SAMPLE_ASSIGNEE_BY_RANGE = "DELETE_SAMPLE_ASSIGNEE_BY_RANGE";
export const SELECTED_SAMPLE_ASSIGNEE_NULL = "SELECTED_SAMPLE_ASSIGNEE_NULL";

export const OPEN_SAMPLE_ASSIGNEE_SIDEBAR = "OPEN_SAMPLE_ASSIGNEE_SIDEBAR";
export const OPEN_SAMPLE_ASSIGNEE_EDIT_SIDEBAR = "OPEN_SAMPLE_ASSIGNEE_EDIT_SIDEBAR";

export const DROP_DOWN_SAMPLE_ASSIGNEES = "DROP_DOWN_SAMPLE_ASSIGNEES";

export const IS_SAMPLE_ASSIGNEE_DATA_LOADED = "IS_SAMPLE_ASSIGNEE_DATA_LOADED";

export const BIND_SAMPLE_ASSIGNEE_BASIC_INFO = "BIND_SAMPLE_ASSIGNEE_BASIC_INFO";

export const SAMPLE_ASSIGNEE_IMAGE_UPLOADING = "SAMPLE_ASSIGNEE_IMAGE_UPLOADING";

export const GET_SAMPLE_ASSIGNEE_DROPDOWN = "GET_SAMPLE_ASSIGNEE_DROPDOWN";
