export const GET_MERCHANDISERS = "GET_MERCHANDISERS";
export const GET_MERCHANDISERS_BY_QUERY = "GET_MERCHANDISERS_BY_QUERY";
export const GET_MERCHANDISER_BY_ID = "GET_MERCHANDISER_BY_ID";
export const ADD_MERCHANDISER = "ADD_MERCHANDISER";
export const UPDATE_MERCHANDISER = "UPDATE_MERCHANDISER";
export const DELETE_MERCHANDISER = "DELETE_MERCHANDISER";
export const DELETE_MERCHANDISER_BY_RANGE = "DELETE_MERCHANDISER_BY_RANGE";
export const SELECTED_MERCHANDISER_NULL = "SELECTED_MERCHANDISER_NULL";
export const OPEN_MERCHANDISER_SIDEBAR = "OPEN_MERCHANDISER_SIDEBAR";
export const OPEN_MERCHANDISER_SIDEBAR_FOR_EDIT = "OPEN_MERCHANDISER_SIDEBAR_FOR_EDIT";
export const DROP_DOWN_MERCHANDISERS = "DROP_DOWN_MERCHANDISERS";

export const IS_MERCHANDISER_DATA_LOADED = "IS_MERCHANDISER_DATA_LOADED";

export const MERCHANDISER_IMAGE_UPLOADING = "MERCHANDISER_IMAGE_UPLOADING";

export const BIND_MERCHANDISER_BASIC_INFO = "BIND_MERCHANDISER_BASIC_INFO";

export const CLEAR_MERCHANDISER_ALL_STATE = "CLEAR_MERCHANDISER_ALL_STATE";

export const GET_BUYER_MERCHANDISER_BY_ID = "GET_BUYER_MERCHANDISER_BY_ID";

export const IS_ASSIGN_BUYER_MODAL_OPEN = "IS_ASSIGN_BUYER_MODAL_OPEN";
