
export const GET_COSTINGS = "GET_COSTINGS";
export const GET_COSTINGS_BY_QUERY = "GET_COSTINGS_BY_QUERY";
export const GET_COSTING_BY_ID = "GET_COSTINGS_BY_ID";
export const GET_SET_COSTING_BY_ID = "GET-SET_COSTINGS_BY_ID";
export const ADD_COSTING = "ADD_COSTING";
export const UPDATE_COSTING = "UPDATE_COSTING";
export const DELETE_COSTING = "DELETE_COSTING";
export const DELETE_COSTINGS_BY_RANGE = "DELETE_COSTINGS_BY_RANGE";

export const DELETE_COSTING_PURCHASE_ORDER_DETAILS = "DELETE_COSTING_PURCHASE_ORDER_DETAILS";

export const SELECTED_COSTING_NULL = "SELECTED_COSTING_NULL";
export const DROP_DOWN_COSTINGS = 'DROP_DOWN_COSTINGS';

export const COSTING_BASIC_INFO = "COSTING_BASIC_INFO";
export const COSTING_SUMMARY_INFO = "COSTING_SUMMARY_INFO";
export const COSTING_GROUP_FOR_COSTING = "COSTING_GROUP_FOR_COSTING";
export const COSTING_ACCESSORIES_DETAILS = "COSTING_ACCESSORIES_DETAILS";
export const COSTING_FABRIC_DETAILS = "COSTING_FABRIC_DETAILS";

export const COSTING_CM_CALCULATION_FOR_SMV = "COSTING_CM_CALCULATION_FOR_SMV";
export const COSTING_CM_CALCULATION_FOR_MACHINE = "COSTING_CM_CALCULATION_FOR_MACHINE";

export const GET_STYLES_DROP_DOWN_BY_PURCHASE_ORDER_ID = "GET_STYLES_DROP_DOWN_BY_PURCHASE_ORDER_ID";

export const GET_SET_STYLE_PREVIOUS_COSTING_HISTORY = "GET_SET_STYLE_PREVIOUS_COSTING_HISTORY";

export const GET_COSTING_SIZE_GROUP_AND_COLORS_HISTORY = "GET_COSTING_SIZE_GROUP_AND_COLORS_HISTORY";
export const GET_COSTING_DROPDOWN_BY_ORDER_ID_AND_STYLE_ID = "GET_COSTING_DROPDOWN_BY_ORDER_ID_AND_STYLE_ID";

export const GET_COSTING_STYLES_PURCHASE_ORDER_DETAILS = "GET_COSTING_STYLES_PURCHASE_ORDER_DETAILS";
export const GET_SET_COSTING_STYLES_PURCHASE_ORDER_DETAILS = "GET_SET_COSTING_STYLES_PURCHASE_ORDER_DETAILS";

export const CLEAR_ALL_COSTING_STATE = "CLEAR_ALL_COSTING_STATE";


export const GET_STYLE_COSTING_DETAILS = "GET_STYLE_COSTING_DETAILS";

export const COSTING_CLONE = "COSTING_CLONE";

export const GET_STYLE_DEFAULT_CATEGORY = "GET_STYLE_DEFAULT_CATEGORY";


export const IS_COSTING_DATA_PROGRESS = "IS_COSTING_DATA_PROGRESS";
export const IS_COSTING_DATA_LOADED = "IS_COSTING_DATA_LOADED";