export const GET_BUDGETS = "GET_BUDGETS";
export const GET_BUDGETS_BY_QUERY = "GET_BUDGETS_BY_QUERY";
export const GET_BUDGET_BY_ID = "GET_BUDGET_BY_ID";
export const ADD_BUDGET = "ADD_BUDGET";
export const UPDATE_BUDGET = "UPDATE_BUDGET";
export const DELETE_BUDGET = "DELETE_BUDGET";
export const DELETE_BUDGET_BY_RANGE = "DELETE_BUDGET_BY_RANGE";
export const OPEN_BUDGET_VIEW_MODAL = "OPEN_BUDGET_VIEW_MODAL";
export const SELECTED_BUDGET_NULL = "SELECTED_BUDGET_NULL";
export const DROP_DOWN_BUDGETS = "DROP_DOWN_BUDGETS";
export const BUYERS_PO_DETAILS_FOR_BUDGET = "BUYERS_PO_DETAILS_FOR_BUDGET";
export const GET_BUDGET_DERAILS = "GET_BUDGET_DERAILS";
export const GET_BUDGET_DERAILS_BY_GROUP_TYPE = "GET_BUDGET_DERAILS_BY_GROUP_TYPE";

export const GET_BUDGETS_BY_BUYER_ID = "GET_BUDGETS_BY_BUYER_ID";

export const GET_BUDGET_DROPDOWN = "GET_BUDGET_DROPDOWN";

export const GET_BUDGET_BUYER_PO_BY_BUYER_ID = "GET_BUDGET_BUYER_PO_BY_BUYER_ID";

export const BIND_BUDGET_BASIC_INFO = "BIND_BUDGET_BASIC_INFO";

export const IS_BUDGET_DATA_LOADED = "IS_BUDGET_DATA_LOADED";

export const CLEAN_ALL_BUDGET_STATES = "CLEAN_ALL_BUDGET_STATES";


export const BIND_SERVICE_COST_SUMMARY = "BIND_SERVICE_COST_SUMMARY";
export const DELETE_BUDGET_ORDER = "DELETE_BUDGET_ORDER";
