
export const GET_PURCHASE_ORDERS = "GET_PURCHASE_ORDERS";
export const GET_PURCHASE_ORDERS_BY_QUERY = "GET_PURCHASE_ORDERS_BY_QUERY";
export const GET_PURCHASE_ORDER_BY_ID = "GET_PURCHASE_ORDERS_BY_ID";
export const GET_PURCHASE_ORDER_DETAILS_BY_ID = "GET_PURCHASE_ORDER_DETAILS_BY_ID";
export const ADD_PURCHASE_ORDER = "ADD_PURCHASE_ORDER";
export const UPDATE_PURCHASE_ORDER = "UPDATE_PURCHASE_ORDER";
export const DELETE_PURCHASE_ORDER = "DELETE_PURCHASE_ORDER";
export const DELETE_PURCHASE_ORDERS_BY_RANGE = "DELETE_PURCHASE_ORDERS_BY_RANGE";
export const SELECTED_PURCHASE_ORDER_NULL = "SELECTED_PURCHASE_ORDER_NULL";

export const GET_STYLES_BY_PO_ID = "GET_STYLES_BY_PO_ID";
export const GET_PURCHASE_ORDER_DROP_DOWN = "GET_PURCHASE_ORDER_DROP_DOWN";


export const OPEN_PURCHASE_ORDER_SIDEBER = "OPEN_PURCHASE_ORDER_SIDEBER";
export const OPEN_PURCHASE_ORDER_FORM = "OPEN_PURCHASE_ORDER_FORM";
export const CONTROL_SET_PURCHASE_ORDER = "CONTROL_SET_PURCHASE_ORDER";
export const CONTROL_SINGLE_PURCHASE_ORDER = "CONTROL_SINGLE_PURCHASE_ORDER";
export const TOTAL_SELECTED_STYLES = "TOTAL_SELECTED_STYLES";

export const ADD_SINGLE_PO_SIZE_COLOR_RATION = "ADD_SINGLE_PO_SIZE_COLOR_RATION";
export const ADD_SET_PO_SIZE_COLOR_RATION = "ADD_SET_PO_SIZE_COLOR_RATION";


export const DELETE_PURCHASE_ORDER_DETAILS = "DELETE_PURCHASE_ORDER_DETAILS";


export const GET_COLOR_SIZE_QUANTITY_BY_PO_DETAILS_ID = "GET_COLOR_SIZE_QUANTITY_BY_PO_DETAILS_ID";

export const GET_PURCHASE_ORDER_DROP_DOWN_BY_BUYER_ID = "GET_PURCHASE_ORDER_DROP_DOWN_BY_BUYER_ID";
export const GET_PURCHASE_ORDER_DETAILS_SIZE_COLOR_QUANTITY_SUMMARY = "GET_PURCHASE_ORDER_DETAILS_SIZE_COLOR_QUANTITY_SUMMARY";
export const GET_PURCHASE_ORDER_DETAILS_SIZE_COLOR_QUANTITY_SUMMARY_DETAILS = "GET_PURCHASE_ORDER_DETAILS_SIZE_COLOR_QUANTITY_SUMMARY_DETAILS";


export const GET_STYLE_PURCHASE_ORDER_DETAILS = "GET_STYLE_PURCHASE_ORDER_DETAILS";
export const BIND_STYLE_PURCHASE_ORDER_DETAILS = "BIND_STYLE_PURCHASE_ORDER_DETAILS";
export const GET_STYLE_PURCHASE_ORDER = "GET_STYLE_PURCHASE_ORDER";
export const BIND_STYLE_PURCHASE_ORDER = "BIND_STYLE_PURCHASE_ORDER";

export const PURCHASE_ORDER_DATA_LOADING = "PURCHASE_ORDER_DATA_LOADING";


export const STYLE_PURCHASE_ORDER_DROPDOWN = "STYLE_PURCHASE_ORDER_DROPDOWN";
