
export const GET_COLORS = 'GET_COLORS';
export const GET_COLORS_BY_QUERY = 'GET_COLORS_BY_QUERY';
export const GET_COLOR_BY_ID = 'GET_COLOR_BY_ID';
export const ADD_COLOR = 'ADD_COLOR';
export const UPDATE_COLOR = 'UPDATE_COLOR';
export const DELETE_COLOR = 'DELETE_COLOR';
export const DELETE_COLORS_BY_RANGE = 'DELETE_COLORS_BY_RANGE';
export const SELECTED_COLOR_NULL = 'SELECTED_COLOR_NULL';

export const BIND_COLOR_DATA = "BIND_COLOR_DATA";

export const GET_COLORS_BY_STYLE_ID = 'GET_COLORS_BY_STYLE_ID';

export const OPEN_COLOR_SIDEBAR = 'OPEN_COLOR_SIDEBAR';
export const OPEN_COLOR_SIDEBAR_FOR_EDIT = 'OPEN_COLOR_SIDEBAR_FOR_EDIT';
export const DROP_DOWN_COLORS = 'DROP_DOWN_COLORS';


export const IS_COLOR_DATA_LOADED = "IS_COLOR_DATA_LOADED";
export const IS_COLOR_DATA_ON_PROGRESS = "IS_COLOR_DATA_ON_PROGRESS";
export const IS_COLOR_DATA_SUBMIT_PROGRESS = "IS_COLOR_DATA_SUBMIT_PROGRESS";
