
export const GET_SIZE_GROUPS = "GET_SIZE_GROUPS";
export const GET_SIZE_GROUPS_BY_QUERY = "GET_SIZE_GROUPS_BY_QUERY";
export const GET_SIZE_GROUP_BY_ID = "GET_SIZE_GROUP_BY_ID";
export const ADD_SIZE_GROUP = "ADD_SIZE_GROUP";
export const UPDATE_SIZE_GROUP = "UPDATE_SIZE_GROUP";
export const DELETE_SIZE_GROUP = "DELETE_SIZE_GROUP";
export const DELETE_SIZE_GROUP_BY_RANGE = "DELETE_SIZE_GROUP_BY_RANGE";
export const SELECTED_SIZE_GROUP_NULL = "SELECTED_SIZE_GROUP_NULL";

export const BIND_SIZE_GROUP_DATA = "BIND_SIZE_GROUP_DATA";

export const OPEN_SIZE_GROUP_SIDEBAR = "OPEN_SIZE_GROUP_SIDEBAR";
export const OPEN_SIZE_GROUP_SIDEBAR_FOR_EDIT = "OPEN_SIZE_GROUP_SIDEBAR_FOR_EDIT";
export const DROP_DOWN_SIZE_GROUPS = "DROP_DOWN_SIZE_GROUPS";


export const IS_SIZE_GROUP_DATA_LOADED = "IS_SIZE_GROUP_DATA_LOADED";
export const IS_SIZE_GROUP_DATA_ON_PROGRESS = "IS_SIZE_GROUP_DATA_ON_PROGRESS";
export const IS_SIZE_GROUP_DATA_SUBMIT_PROGRESS = "IS_SIZE_GROUP_DATA_SUBMIT_PROGRESS";
