export const GET_BUYER_AGENTS = "GET_BUYER_AGENTS";
export const GET_BUYER_AGENTS_BY_QUERY = "GET_BUYER_AGENTS_BY_QUERY";
export const GET_BUYER_AGENT_BY_ID = "GET_BUYER_AGENT_BY_ID";
export const ADD_BUYER_AGENT = "ADD_BUYER_AGENT";
export const UPDATE_BUYER_AGENT = "UPDATE_BUYER_AGENT";
export const DELETE_BUYER_AGENT = "DELETE_BUYER_AGENT";
export const DELETE_BUYER_AGENT_BY_RANGE = "DELETE_BUYER_AGENT_BY_RANGE";
export const SELECTED_BUYER_AGENT_NULL = "SELECTED_BUYER_AGENT_NULL";
export const OPEN_BUYER_AGENT_SIDEBAR = "OPEN_BUYER_AGENT_SIDEBAR";
export const OPEN_BUYER_AGENT_SIDEBAR_FOR_EDIT = "OPEN_BUYER_AGENT_SIDEBAR_FOR_EDIT";
export const DROP_DOWN_BUYER_AGENTS = "DROP_DOWN_BUYER_AGENTS";

export const IS_AGENT_DATA_LOADED = "IS_AGENT_DATA_LOADED";

export const AGENT_IMAGE_UPLOADING = "AGENT_IMAGE_UPLOADING";

export const BIND_AGENT_BASIC_INFO = "BIND_AGENT_BASIC_INFO";

export const CLEAR_AGENT_ALL_STATE = "CLEAR_AGENT_ALL_STATE";
