
export const GET_USERS_BY_QUERY = "GET_USERS_BY_QUERY";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const GET_USER_PERMISSION_BY_USER_ID = "GET_USER_PERMISSION_BY_USER_ID";
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

export const IS_USER_DATA_LOADED = "IS_USER_DATA_LOADED";

export const IS_USER_DATA_PROGRESS = "IS_USER_DATA_PROGRESS";
export const IS_USER_DATA_SUBMIT_PROGRESS = "IS_USER_DATA_SUBMIT_PROGRESS";

export const GET_USER_DROPDOWN = "GET_USER_DROPDOWN";


export const IS_USER_ADD_FORM_SIDEBAR_OPEN = "IS_USER_ADD_FORM_SIDEBAR_OPEN";
export const IS_USER_EDIT_FORM_SIDEBAR_OPEN = "IS_USER_EDIT_FORM_SIDEBAR_OPEN";

export const IS_USER_PHOTO_UPLOADED = "IS_USER_EDIT_FORM_SIDEBAR_OPEN";

export const BIND_USER_BASIC_INFO = "BIND_USER_BASIC_INFO";

export const CLEAR_USER_ALL_STATE = "CLEAR_USER_ALL_STATE";
