export const GET_ITEM_SUB_GROUP = "GET_ITEM_SUB_GROUP";
export const GET_ITEM_SUB_GROUP_BY_QUERY = "GET_ITEM_SUB_GROUP_BY_QUERY";
export const GET_ITEM_SUB_GROUP_BY_ID = "GET_ITEM_SUB_GROUP_BY_ID";
export const ADD_ITEM_SUB_GROUP = "ADD_ITEM_SUB_GROUP";
export const UPDATE_ITEM_SUB_GROUP = "UPDATE_ITEM_SUB_GROUP";
export const DELETE_ITEM_SUB_GROUP = "DELETE_ITEM_SUB_GROUP";
export const DELETE_ITEM_SUB_GROUP_BY_RANGE = "DELETE_ITEM_SUB_GROUP_BY_RANGE";
export const SELECTED_ITEM_SUB_GROUP_NULL = "SELECTED_ITEM_SUB_GROUP_NULL";


export const OPEN_ITEM_SUB_GROUP_SIDEBAR = "OPEN_ITEM_SUB_GROUP_SIDEBAR";
export const DROP_DOWN_ITEM_SUB_GROUP = "DROP_DOWN_ITEM_SUB_GROUP";

export const GET_FABRIC_SUB_CATEGORIES = "GET_FABRIC_SUB_CATEGORIES";